#Insurance Tratamento

In [93]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [94]:
import pandas as pd
import sklearn
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle as pkl
import numpy as np

from sklearn.naive_bayes import GaussianNB

In [95]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [96]:
insurance = pd.read_csv("insurance.csv")

In [97]:
insurance

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [98]:
insurance.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [99]:
insurance = insurance.values

In [100]:
sex_encoder = LabelEncoder()
region_encoder = LabelEncoder()
smoker_encoder = LabelEncoder()

In [101]:
insurance[:,1] = sex_encoder.fit_transform(insurance[:,1])
insurance[:,4] = smoker_encoder.fit_transform(insurance[:,4])
insurance[:,5] = region_encoder.fit_transform(insurance[:,5])

In [102]:
insurance

array([[19, 0, 27.9, ..., 1, 3, 16884.924],
       [18, 1, 33.77, ..., 0, 2, 1725.5523],
       [28, 1, 33.0, ..., 0, 2, 4449.462],
       ...,
       [18, 0, 36.85, ..., 0, 2, 1629.8335],
       [21, 0, 25.8, ..., 0, 3, 2007.945],
       [61, 0, 29.07, ..., 1, 1, 29141.3603]],
      shape=(1338, 7), dtype=object)

In [103]:
X = insurance[:,:5]
Y = insurance[:,6]

In [104]:
X

array([[19, 0, 27.9, 0, 1],
       [18, 1, 33.77, 1, 0],
       [28, 1, 33.0, 3, 0],
       ...,
       [18, 0, 36.85, 0, 0],
       [21, 0, 25.8, 0, 0],
       [61, 0, 29.07, 0, 1]], shape=(1338, 5), dtype=object)

In [105]:
Y

array([16884.924, 1725.5523, 4449.462, ..., 1629.8335, 2007.945,
       29141.3603], shape=(1338,), dtype=object)

In [106]:
X, Y = load_iris(return_X_y=True)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size = 0.5, random_state = 0)


In [107]:
X_train.shape, X_test.shape, Y_test.shape, Y_train.shape

((75, 4), (75, 4), (75,), (75,))

In [108]:
with open('insurance.pkl', 'wb') as f:
    pkl.dump([X_train, X_test, Y_train, Y_test], f)